export const AUTH_USER = 'AUTH_USER';
export const SET_USERNAME = 'SET_USERNAME';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SIGNUP_ONCHANGE = 'SIGNUP_ONCHANGE';
export const CLEAR_SIGNUP = 'CLEAR_SIGNUP';
export const SET_SIGNUP_ERRORS = 'SET_SIGNUP_ERRORS';
export const CLEAR_SIGNUP_ERRORS = 'CLEAR_SIGNUP_ERRORS';